//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorStep.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddToCart
    {
        public int CartId { get; set; }
        public string SecretToken { get; set; }
        public int BikeId { get; set; }
        public string InitiatedThrough { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
    }
}
