//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorStep.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BikeInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BikeInformation()
        {
            this.BikeCityWises = new HashSet<BikeCityWise>();
            this.ImageDetails = new HashSet<ImageDetail>();
            this.CartDetails = new HashSet<CartDetail>();
        }
    
        public int BikeId { get; set; }
        public string BikeBrand { get; set; }
        public Nullable<decimal> BikeModel { get; set; }
        public Nullable<int> BikeRegistrationYear { get; set; }
        public string BikeKmDriven { get; set; }
        public string BikeDescription { get; set; }
        public Nullable<decimal> BikePrice { get; set; }
        public Nullable<System.DateTime> BikePreferDateTimeIn { get; set; }
        public Nullable<System.DateTime> BikePreferDateTimeOut { get; set; }
        public string BikeOwnerName { get; set; }
        public string BikeResonForSale { get; set; }
        public string BikeEngineNo { get; set; }
        public string BikeChasisNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BikeCityWise> BikeCityWises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageDetail> ImageDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartDetail> CartDetails { get; set; }
    }
}
