//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorStep.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageDetail
    {
        public int ImgId { get; set; }
        public int BikeId { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public string ImgPath { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual BikeInformation BikeInformation { get; set; }
    }
}
