//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorStep.Infrastructure.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ObickeEntities : DbContext
    {
        public ObickeEntities()
            : base("name=ObickeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BikeCityWise> BikeCityWises { get; set; }
        public virtual DbSet<BikeInformation> BikeInformations { get; set; }
        public virtual DbSet<CityArea> CityAreas { get; set; }
        public virtual DbSet<CityTable> CityTables { get; set; }
        public virtual DbSet<ImageDetail> ImageDetails { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<PlacedOrder> PlacedOrders { get; set; }
        public virtual DbSet<TransactionDetail> TransactionDetails { get; set; }
        public virtual DbSet<MobileOtp> MobileOtps { get; set; }
        public virtual DbSet<AddToCart> AddToCarts { get; set; }
        public virtual DbSet<CartDetail> CartDetails { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    
        public virtual ObjectResult<stpGetBikedetailsInfo_Result> stpGetBikedetailsInfo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stpGetBikedetailsInfo_Result>("stpGetBikedetailsInfo", idParameter);
        }
    }
}
