//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorStep.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlacedOrder
    {
        public int POId { get; set; }
        public int UserId { get; set; }
        public int BikeId { get; set; }
        public int PaymentId { get; set; }
        public bool IsOpen { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        public virtual PaymentDetail PaymentDetail { get; set; }
    }
}
