//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorStep.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int TransId { get; set; }
        public string UserName { get; set; }
        public string CustomerId { get; set; }
        public string MobileNo { get; set; }
        public string TxnId { get; set; }
        public decimal TxnAmount { get; set; }
        public string Currency { get; set; }
        public string OrderId { get; set; }
        public string EmailId { get; set; }
        public string TxnStatus { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseMsg { get; set; }
        public string PaymentMode { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> TxnDate { get; set; }
        public string GatewayName { get; set; }
        public string BankTxnId { get; set; }
        public string BankName { get; set; }
        public Nullable<System.DateTime> PaymentInitiatedDateTime { get; set; }
        public Nullable<System.DateTime> PaymentCompletedDateTime { get; set; }
    }
}
