//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorStep.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetail()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        public int UserId { get; set; }
        public string Fullname { get; set; }
        public string UserEmailId { get; set; }
        public string MobileNo { get; set; }
        public string SecretToken { get; set; }
        public string CurrentLocation { get; set; }
        public Nullable<int> AddressType { get; set; }
        public string LandMark { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TimeFrom { get; set; }
        public Nullable<int> TimeTo { get; set; }
        public string AMPM { get; set; }
        public Nullable<int> City { get; set; }
        public string Pincode { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
    }
}
